{{- if and .Values.authApi.enabled .Values.authApi.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.authApi.name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.authApi.name }}
  minReplicas: {{ .Values.authApi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.authApi.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.authApi.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}

